# Generated by Django 5.0.6 on 2024-06-05 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OyoqKiyimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('tavsif', models.TextField()),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('olchamlari', models.CharField(max_length=50)),
                ('zaxiradagi_soni', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Ayollar oyoq kiyimlari',
                'verbose_name_plural': 'Ayollar oyoq kiyimlari',
            },
        ),
        migrations.CreateModel(
            name='OyoqKiyimRasmlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rangi', models.CharField(choices=[('qizil', 'Qizil'), ('ko`k', 'Ko`k'), ('yashil', 'Yashil'), ('oq', 'Oq'), ('qora', 'Qora'), ('sariq', 'Sariq'), ('to`q sariq', 'To`q sariq'), ('moviy', 'Moviy'), ('binafsha', 'Binafsha'), ('kulrang', 'Kulrang'), ('jigar rang', 'Jigar rang'), ('tilla rang', 'Tilla rang')], default='oq', max_length=50)),
                ('rasmi', models.ImageField(upload_to='oyoqkiyimlar/')),
                ('nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Oyoq_Kiyimlar', to='shoes.oyoqkiyimlar')),
            ],
            options={
                'verbose_name': 'Ayollar oyoq kiyimlari rasmlari',
                'verbose_name_plural': 'Ayollar oyoq kiyimlari rasmlari',
            },
        ),
    ]
