# Generated by Django 5.0.6 on 2024-06-05 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boshqa_mahuslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('tavsif', models.TextField()),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Boshqa',
                'verbose_name_plural': 'Boshqa',
            },
        ),
        migrations.CreateModel(
            name='boshqa_mahuslot_rasmlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasmi', models.ImageField(upload_to='Boshqa/')),
                ('nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Boshqa', to='boshqa.boshqa_mahuslot')),
            ],
            options={
                'verbose_name': 'Boshqa rasmlari',
                'verbose_name_plural': 'Boshqa rasmlari',
            },
        ),
    ]
